CryptoNexa-dev/CryptoNexa/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from CryptoNexa import views, settings

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', views.index, name='index'),
  path('', include('core.urls')),
  path('', include('Newsletter.urls')),
  path('', include('ContactUS.urls')),
  path('currencyExchange/', include('currencyExchange.urls')),
  path('', include('payments.urls')),
  path('', include('BuySell.urls')),
  path('', include('portfolio.urls')),
  path('', include('support.urls')),
  path('filter_crypto_data', views.filter_crypto_data, name='filter_crypto_data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CryptoNexa-dev/core/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'core'

urlpatterns = [
    path('register/', csrf_exempt(views.register), name='register'),
    path('login/', csrf_exempt(views.user_login), name='login'),
    path('logout/', csrf_exempt(views.user_logout), name='logout'),
    path('profile/<int:id>', csrf_exempt(views.user_profile), name='profile'),
    path('edit_profile/<int:id>', csrf_exempt(views.user_edit_profile), name='edit_profile'),
    path('crypto/<slug:slug>/', views.crypto_detail, name='crypto_detail'),
    path('get_updated_crypto_data/<int:fetch_live_data>', views.get_updated_crypto_data,
         name='get_updated_crypto_data'),
    path('watchlist/', csrf_exempt(views.watchlist), name='watchlist'),
    path('watchlist/<int:watchlist_id>/', views.watchlist, name='watchlist'),
    path('create_watchlist/', csrf_exempt(views.create_watchlist), name='create_watchlist'),
    path('edit_watchlist_name/<int:watchlist_id>/', csrf_exempt(views.edit_watchlist_name), name='edit_watchlist_name'),
    path('payment_history/', csrf_exempt(views.payment_history), name='payment_history'),
    path('payment_history/',csrf_exempt(views.payment_history),name='payment_history'),
    path('currency_converter/',csrf_exempt(views.currency_converter), name='currency_converter')

    # Add other URL patterns as needed for your application
]

CryptoNexa-dev/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Watchlist, Cryptocurrency


class CustomUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'photo_id']  # Add custom fields as needed


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'photo_id']  # Add custom fields as needed


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'photo_id']


class WatchlistForm(forms.ModelForm):
    cryptocurrencies = forms.ModelMultipleChoiceField(
        queryset=Cryptocurrency.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='Select Cryptocurrencies',
        required=False
    )

    class Meta:
        model = Watchlist
        fields = ['name', 'cryptocurrencies']
        widgets = {
            'name': forms.TextInput(attrs={'required': False}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        model = User  # Use the User model from Django's auth module
        fields = ['first_name', 'last_name', 'email']


class CurrencyConverterForm(forms.Form):
    amount = forms.DecimalField(label='Amount', min_value=1e-8, max_value=1000000000000, initial=1)
    base_currency = forms.CharField(label='Base Currency', max_length=100)
    convert_currency = forms.CharField(label='Convert To', max_length=100)

CryptoNexa-dev/templates/paymentCheckout/payment_cancelled.html
{% extends 'CryptoNexa/base.html' %}

{% block title %}Payment Unsuccessful{% endblock %}

{% block content %}
    <div class="card error-card mt-5">
        <div class="card-body">
            <h1 class="card-title">Payment Unsuccessful</h1>
            <p class="card-text">We're sorry, but there was an issue processing your payment.</p>
            <a class="btn btn-danger" style="font-size: 15px; width: 15%;" href="{% url 'index' %}">Back to homepage</a>
        </div>
    </div>
{% endblock %}

CryptoNexa-dev/templates/paymentCheckout/payment_checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
    <title>Buy cool new product</title>
    <script src="https://js.stripe.com/v3/"></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/payment_checkout.css' %}">

</head>
<body style="background-color: whitesmoke">
<div class="container">
    <div class="center-div">
        <div class="order-header">
            <h3>Order Summary</h3>
            <h6>Here's what you've ordered. If you're all good, proceed to pay and complete your transaction.</h6>
        </div>
        <div class="crypto-details">
            <div class="textLeft">
                <div class="title">You Get</div>
                <div class="crypto-div">
                    <div>~{{ user_transaction.quantity }} &nbsp {{ user_transaction.coin }}</div>
                </div>
            </div>
            <div class="textLeft">
                <div class="title">You Spent</div>
                <div class="total-spent">
                    <div>{{ user_transaction.total_spent }} &nbsp{{ user_transaction.currency }}</div>
                    <div class="transaction-fee">{{ user_transaction.transaction_fee }} {{ user_transaction.currency }}
                        fee included
                    </div>
                </div>
            </div>
        </div>
        <form action="/create-checkout-session" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user_transaction" value="{{ user_transaction.id }}">
            <button type="submit" id="checkout-button" class="btn btn-outline-primary">Proceed to Pay</button>
        </form>
    </div>
</div>
</body>
</html>

CryptoNexa-dev/templates/paymentCheckout/payment_sell_form.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/payment_checkout.css' %}">
</head>
<body style="background-color: whitesmoke">
<div class="container">
    <div class="center-div">
        <div class="order-header">
            <h6>Transaction ID: #{{ tran_id }}</h6>
            <h3>Order Summary</h3>
            <h6>Here's what you want to Sell. Please add the Account Details.</h6>
        </div>
        <center>
        <div class="crypto-details">
        <table>
            <tr>
                <td>
                    <div class="textLeft">
                    <div class="title">You Selling</div>
                    <div class="total-spent">
                        <div>{{ user_transaction.quantity }} {{ user_transaction.coin }}</div>
                    </div>
                </div>
                </td>
                <td>
                    <div class="textLeft">
                        <div class="title">You Get</div>
                        <div class="total-spent">
                            <div>{{ user_transaction.currency  }} {{ user_transaction.total_spent }}</div>
                        </div>
                    </div>
                </td>
            </tr>

        </table>
         <div class="transaction-fee">{{ user_transaction.transaction_fee }} {{ user_transaction.currency }} fees included</div>
         </div>
        </center>
        <form method="POST">
            {% csrf_token %}
        <div class="container-sell">
                {% for field in form %}
                    {% if field.name == "amount" %}
                        <div class="form-floating mb-2">
                        <input class="form-control" name="amount" id="id_amount" value="{{ field.value }}" readonly>
                            <label for="id_amount">{{ field.label }}</label>
                        </div>
                     {% else %}
                            <div class="form-floating mb-2">
                                {{ field }}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            </div>
                    {% endif %}
                {% endfor %}
        </div>
            <input type="submit" id="checkout-button" class="btn btn-dark" value="Sell">
        </form>
    </div>
</div>
</body>
</html>

CryptoNexa-dev/templates/paymentCheckout/payment_successful.html
{% extends 'CryptoNexa/base.html' %}

{% block title %}Payment Successful{% endblock %}

{% block content %}
    <div class="container">
    <div class="card success-card mt-5">
        <div class="card-body">
            <h2 class="card-title">Order Details</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Type: {{ transaction_obj.type }}</li>
                <li class="list-group-item">Coin: {{ transaction_obj.coin }}</li>
                <li class="list-group-item">Transaction ID: {{ transaction_obj.id }}</li>
                <li class="list-group-item">Payment ID: {{ user_payment.id }}</li>
            </ul>
        </div>
    </div>

    <div class="card thank-you-card mt-3">
        <div class="card-body">
            <h3 class="card-title">Thank you for choosing us, {{ user_object.first_name }}!</h3>
            <p class="card-text">Click here to return to the homepage </p>
            <a class="btn btn-primary" style="font-size: 15px; width: 15%" href="{% url 'index' %}">Back to homepage</a>
        </div>
    </div>
    <br><br>
    </div>
{% endblock %}