CryptoNexa-dev/CryptoNexa/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from CryptoNexa import views, settings

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', views.index, name='index'),
  path('', include('core.urls')),
  path('', include('Newsletter.urls')),
  path('', include('ContactUS.urls')),
  path('currencyExchange/', include('currencyExchange.urls')),
  path('', include('payments.urls')),
  path('', include('BuySell.urls')),
  path('', include('portfolio.urls')),
  path('', include('support.urls')),
  path('filter_crypto_data', views.filter_crypto_data, name='filter_crypto_data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CryptoNexa-dev/core/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'core'

urlpatterns = [
    path('register/', csrf_exempt(views.register), name='register'),
    path('login/', csrf_exempt(views.user_login), name='login'),
    path('logout/', csrf_exempt(views.user_logout), name='logout'),
    path('profile/<int:id>', csrf_exempt(views.user_profile), name='profile'),
    path('edit_profile/<int:id>', csrf_exempt(views.user_edit_profile), name='edit_profile'),
    path('crypto/<slug:slug>/', views.crypto_detail, name='crypto_detail'),
    path('get_updated_crypto_data/<int:fetch_live_data>', views.get_updated_crypto_data,
         name='get_updated_crypto_data'),
    path('watchlist/', csrf_exempt(views.watchlist), name='watchlist'),
    path('watchlist/<int:watchlist_id>/', views.watchlist, name='watchlist'),
    path('create_watchlist/', csrf_exempt(views.create_watchlist), name='create_watchlist'),
    path('edit_watchlist_name/<int:watchlist_id>/', csrf_exempt(views.edit_watchlist_name), name='edit_watchlist_name'),
    path('payment_history/', csrf_exempt(views.payment_history), name='payment_history'),
    path('payment_history/',csrf_exempt(views.payment_history),name='payment_history'),
    path('currency_converter/',csrf_exempt(views.currency_converter), name='currency_converter')

    # Add other URL patterns as needed for your application
]

CryptoNexa-dev/support/urls.py
from django.contrib import admin
from django.urls import path, include
from support import views

app_name = 'support'

urlpatterns = [
    path('support/issue_creation/', views.issue_creation, name='issue_creation'),
    path('support/list_issues/', views.list_issues, name='list_issues'),
]

CryptoNexa-dev/CryptoNexa/forms.py
from django import forms

# Choices for greater than or less than
GT_LT_CHOICES = [
    ('gt', 'Greater Than'),
    ('lt', 'Less Than'),
]

INFINITE_SUPPLY_CHOICES = [
    (True, 'Yes'),
    (False, 'No'),
]


class CryptoFilterForm(forms.Form):
    name = forms.CharField(required=False, label='Name', max_length=50, widget=forms.TextInput(attrs={'class': 'custom-input'}))
    num_market_pairs = forms.IntegerField(required=False, label='Number of Market Pairs',
                                          widget=forms.NumberInput(attrs={'class': 'custom-input'}))
    circulating_supply = forms.DecimalField(required=False, label='Circulating Supply', max_digits=20, decimal_places=2,
                                            widget=forms.NumberInput(attrs={'class': 'custom-input'}))
    total_supply = forms.DecimalField(required=False, label='Total Supply', max_digits=20, decimal_places=2,
                                      widget=forms.NumberInput(attrs={'class': 'custom-input'}))
    max_supply = forms.DecimalField(required=False, label='Max Supply', max_digits=20, decimal_places=2,
                                    widget=forms.NumberInput(attrs={'class': 'custom-input'}))
    infinite_supply = forms.ChoiceField(required=False, label='Infinite Supply', choices=INFINITE_SUPPLY_CHOICES,
                                       widget=forms.RadioSelect(attrs={'class': 'custom-input-radio'}))

    """Quote Related"""
    price_min = forms.DecimalField(required=False, label='Min Price', max_digits=20, decimal_places=2,
                               widget=forms.NumberInput(attrs={'class': 'custom-input'}))
    price_max = forms.DecimalField(required=False, label='Max Price', max_digits=20, decimal_places=2,
                               widget=forms.NumberInput(attrs={'class': 'custom-input'}))

    def clean(self):
        cleaned_data = super().clean()
        price_min = cleaned_data.get('price_min')
        price_max = cleaned_data.get('price_max')

        if price_min is not None and price_max is not None and price_min > price_max:
            raise forms.ValidationError('Min Price cannot be greater than Max Price.')

        return cleaned_data

CryptoNexa-dev/CryptoNexa/views.py
import decimal

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from CryptoNexa.forms import CryptoFilterForm
from core.apis.helper_functions import process_crypto_data, keep_two_chars_after_dot
from core.apis.coinmarketcap.fetch_data import fetch_data, get_dummy_data
from core.models import Cryptocurrency, Quote
from django.shortcuts import render
from core.apis.coinmarketcap.fetch_data import fetch_data, convert_usd_to_cad
from core.models import Cryptocurrency, Quote, FooterList

from core.models import User


def index(request):
    if request.session.get('currency') is None:
        request.session['currency'] = "USD"
        session_cur = "USD"
    else:
        session_cur = request.session.get('currency')
    context = {}
    error = ''
    # fetched_data_from_api_session_cur = fetch_data(session_cur)
    fetched_data_from_api_session_cur = get_dummy_data(session_cur)
    fetched_status = fetched_data_from_api_session_cur.get('status')

    if fetched_status.get('error_code') != 0:
        error = 'An error occurred while fetching the data.'
        context['error_message'] = error
        return render(request, 'CryptoNexa/index.html', context=context)

    crypto_data = fetched_data_from_api_session_cur.get('data')
    crypto_to_send = update_crypto_details(crypto_data, session_cur)
    cryptos = process_crypto_data(crypto_to_send, session_cur, many=True)
    if request.user.id is None:
        context['cryptos'] = cryptos
    else:
        user_id = request.user.id
        user = User.objects.get(id=user_id)
        context["user"] = user
    context['session_cur'] = session_cur
    context['cryptos'] = cryptos
    context['update_values'] = True
    context['filters_provided'] = False
    footer_items = FooterList.objects.all()
    context['footer_items'] = footer_items

    return render(request, 'CryptoNexa/index.html', context=context)


def update_crypto_details(crypto_data, session_cur, filters=None):
    if filters:
        filtered_crypto = Cryptocurrency.objects.all()

        if filters.get('name') is not None and filters.get('name') != "":
            filtered_crypto = filtered_crypto.filter(slug__contains=filters.get('name').lower())

        if filters.get('num_market_pairs') is not None:
            filtered_crypto = filtered_crypto.filter(slug=filters.get('num_market_pairs'))

        if filters.get('circulating_supply') is not None:
            filtered_crypto = filtered_crypto.filter(circulating_supply=filters.get('circulating_supply'))

        if filters.get('total_supply') is not None:
            filtered_crypto = filtered_crypto.filter(total_supply=filters.get('total_supply'))

        if filters.get('max_supply') is not None:
            filtered_crypto = filtered_crypto.filter(max_supply=filters.get('max_supply'))

        if filters.get('price_min') is not None:
            filtered_crypto = filtered_crypto.filter(price__gt=filters.get('price_min'))

        if filters.get('price_max') is not None:
            filtered_crypto = filtered_crypto.filter(price__lt=filters.get('price_max'))


        if filters.get('infinite_supply') == "True":
            filtered_crypto = filtered_crypto.filter(infinite_supply=True)
        elif filters.get('infinite_supply') == "False":
            filtered_crypto = filtered_crypto.filter(infinite_supply=False)


        return filtered_crypto

    crypto_ids = []
    for current_crypto in crypto_data:
        quote_obj, created = Quote.objects.get_or_create(currency_slug=current_crypto.get('slug'))
        if quote_obj.data is not None and quote_obj.data.get(session_cur) is None:
            new_data = current_crypto.get('quote')
            quote_obj.data[str(session_cur)] = new_data.get(session_cur)
        else:
            quote_obj.data = current_crypto.get('quote')
        quote_obj.currency_symbol = current_crypto.get('symbol')
        quote_obj.save()

        try:
            crypto_obj = Cryptocurrency.objects.get(slug=current_crypto.get('slug'))
            crypto_obj.quote = quote_obj
        except ObjectDoesNotExist as e:
            crypto_obj = Cryptocurrency.objects.create(slug=current_crypto.get('slug'), quote=quote_obj)
        crypto_obj.name = current_crypto.get('name')
        crypto_obj.symbol = current_crypto.get('symbol')
        crypto_obj.num_market_pairs = current_crypto.get('num_market_pairs')
        crypto_obj.circulating_supply = current_crypto.get('circulating_supply')
        crypto_obj.total_supply = current_crypto.get('total_supply')
        crypto_obj.max_supply = current_crypto.get('max_supply')
        crypto_obj.infinite_supply = current_crypto.get('infinite_supply')
        crypto_obj.date_added = current_crypto.get('date_added')
        crypto_obj.last_updated = current_crypto.get('last_updated')
        price = float(current_crypto.get('quote').get(session_cur).get('price'))
        price = "{:.2f}".format(price)
        crypto_obj.price = price
        crypto_ids.append(crypto_obj.pk)
        crypto_obj.save()

    saved_cryptos_queryset = Cryptocurrency.objects.filter(id__in=crypto_ids)
    return saved_cryptos_queryset


def filter_crypto_data(request):
    if request.session.get('currency') is None:
        request.session['currency'] = "USD"
        session_cur = "USD"
    else:
        session_cur = request.session.get('currency')
    context = {}
    if request.method == "POST":
        submitted_form = CryptoFilterForm(request.POST)
        if not submitted_form.is_valid():
            return render(request, 'crypto/crypto_list_filter_modal.html', {"form": submitted_form})

        fetched_data_from_api_session_cur = get_dummy_data(session_cur)
        fetched_status = fetched_data_from_api_session_cur.get('status')

        if fetched_status.get('error_code') != 0:
            error = 'An error occurred while fetching the data.'
            context['error_message'] = error
            return render(request, 'CryptoNexa/index.html', context=context)

        crypto_data = fetched_data_from_api_session_cur.get('data')
        crypto_to_send = update_crypto_details(crypto_data, session_cur, filters=submitted_form.cleaned_data)
        cryptos = process_crypto_data(crypto_to_send, session_cur, many=True)
        context['update_values'] = False
        context['cryptos'] = cryptos
        context['filters_provided'] = True
        context['session_cur'] = session_cur
        context['crypto_count'] = len(cryptos)
        return render(request, 'CryptoNexa/index.html', context=context)

    else:
        form = CryptoFilterForm()

    context['form'] = form
    return render(request, 'crypto/crypto_list_filter_modal.html', context)

CryptoNexa-dev/templates/CryptoNexa/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome to CryptoNexa!{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% csrf_token %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="{% static 'css/crypto_detail.css' %}" rel="stylesheet">
    <script src="{% static 'js/buysell.js' %}"></script>
    {% block head %}
    {% endblock %}

</head>
<body class="d-flex flex-column min-vh-100">

<div class="top-bar bg-light">
    <div class="top-bar-left me-auto mb-2 mb-lg-0">
        <div class="top-bar-left-hero"><span><a href="{% url 'index' %}" class="text-decoration-none text-dark">CrytoNexa</a></span>
        </div>
        <div><span><a href="{% url 'core:currency_converter' %}"
                      class="text-decoration-none text-dark">Converter</a></span></div>
        <div><span><a href="{% url 'news_list' %}" class="text-decoration-none text-dark">Newsletter</a></span></div>
        <div><span><a href="{% url 'support:issue_creation' %}"
                      class="text-decoration-none text-dark">Support</a></span></div>
    </div>
    <div class="top-bar-right">
        <div style="margin-right: 15px;"><span><a href="{% url 'core:watchlist' %}"
                                                  style="text-decoration: none; color: inherit;">Watchlist</a></span>
        </div>
        <div><span><a href="{% url 'portfolio' %}" class="text-decoration-none text-dark" style="margin-right: 10px">Portfolio</a></span></div>
        <a href="{% url 'currency_exchange' %}" id="openModal">
            <button type="button" class="btn btn-outline-primary">{{ request.session.currency }}</button>
        </a>
        {% if user.is_authenticated %}
            <div class="dropdown">
                <button class="btn btn-secondary" type="button" id="profileDropdown"
                        data-bs-toggle="dropdown" aria-expanded="false"
                        style="background-color: #f8f8f8; border:none;">
                    <img style="width: 30px; height: 30px; border-radius: 50%;"
                         src="{% static 'images/profile.jpg' %}" alt="Profile image">
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                    <a href="{% url 'core:edit_profile' user.id %}" style="text-decoration: none; color: #333">
                        <li style="padding: 10px">
                            <div class="d-flex align-items-center">
                                <img src="{% static 'images/profile.jpg' %}" alt="User Profile Image"
                                     class="rounded-circle" style="width: 40px; height: 40px;">
                                <div class="ms-3">
                                    <p class="fw-bold mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                                    <p class="text-muted mb-0">{{ user.email }}</p>
                                </div>
                            </div>
                        </li>
                    </a>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'core:watchlist' %}">Watchlist</a></li>
                    <li><a class="dropdown-item" href="{% url 'portfolio' %}">Portfolio</a></li>
                    <li><a class="dropdown-item" href="{% url 'support:list_issues' %}">Your Issue Tickets</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:payment_history' %}">Payment History</a></li>
                    <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
                </ul>
            </div>
        {% else %}
            <a href="{% url 'core:login' %}">
                <button type="button" class="btn btn-outline-primary">Log In</button>
            </a>
            <a href="{% url 'core:register' %}">
                <button type="button" class="btn btn-primary">Sign Up</button>
            </a>
        {% endif %}
    </div>
</div>
<div id="content" class="flex-grow-1">
    {% block content %}
        <!-- Specific page content goes here -->
    {% endblock %}
    {% block body %}
    {% endblock %}
    {% block currencypopup %}
    {% endblock %}
    {% block crypto_filter %}
    {% endblock %}
</div>

{% block footer %}
    {% include 'CryptoNexa/footer.html' with footer_items=footer_items %}
{% endblock %}
</body>
</html>

CryptoNexa-dev/templates/CryptoNexa/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to CryptoNexa!</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% csrf_token %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="form-container">
    <h3 style="text-align: center; padding-top: 10px;">Login</h3>
    <form class="login-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Email:</label>
            {{ form.username }}
            {#            {% for error in form.username.errors %}#}
            {#                <p class="error-message">{{ error }}</p>#}
            {#            {% endfor %}#}
        </div>

        <div class="form-group">
            <label for="{{ form.password.id_for_label }}">Password:</label>
            {{ form.password }}
            {#            {% for error in form.password.errors %}#}
            {#                <p class="error-message">{{ error }}</p>#}
            {#            {% endfor %}#}
        </div>

        {% if form.errors %}
            {{ form.non_field_errors }}
            {#            {{ form.username.error_messages }}#}
            {#            {{ form.password.error_messages }}#}
        {% endif %}
        {% if next %}
            {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.</p>
            {% else %}
                <p>Please login to see this page.</p>
            {% endif %}
        {% endif %}

        <button type="submit" class="btn btn-primary button">Login</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
    <p class="register-link">Don't have an account? <a href="{% url 'core:register' %}">Register</a></p>
</div>
</body>

CryptoNexa-dev/templates/CryptoNexa/watchlist.html
{% extends 'CryptoNexa/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .crypto-list {
            & label {
                display: flex;
                justify-content: flex-start;
                align-items: center;
                padding: 12px 8px;
                border-radius: 8px;
                cursor: pointer;

                & input {
                    margin-right: 10px;
                }
            }
        }
    </style>

{% endblock %}
{% block content %}
    <div class="container mt-4">
        {% if selected_watchlist %}
            <div class="row">
                <div class="col">
                    <div style="display: flex;">
                        <h2>{{ selected_watchlist.name }}</h2>
                        <button id="editNameBtn" class="btn btn-light" data-bs-toggle="modal"
                                data-bs-target="#editNameModal"
                                style="margin-left: 10px; padding: 6px 6px; background: #fff;">
                            <img src="{% static 'svg/edit.svg' %}" style="height: 20px; width: 20px"
                                 alt="Your Icon">
                        </button>
                        <button id="toggleWatchlists" class="btn btn-light" data-bs-toggle="modal"
                                data-bs-target="#selectWatchlistModal"
                                style="margin-left: 10px; padding: 6px 6px; background: #fff;">
                            <img src="{% static 'svg/arrow-down.svg' %}" style="height: 20px; width: 20px"
                                 alt="Your Icon">
                        </button>
                    </div>
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#addAssetModal" id="addAssetButton">
                        Add Asset
                    </button>
                </div>
            </div>

            {% if cryptocurrencies %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th><i class="currency-icon"></i> Price</th>
                        <th>1h%</th>
                        <th>24h%</th>
                        <th><i class="currency-icon"></i> MarketCap</th>
                        <th><i class="currency-icon"></i> Volume (24h)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for crypto in cryptocurrencies %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'core:crypto_detail' crypto.slug %}">{{ crypto.name }}</a></td>
                            <td><i class="currency-icon"></i><span class="price-class"> {{ crypto.price }}</span></td>
                            <td class="{% if crypto.percent_change_1h < 0 %}text-danger{% elif crypto.percent_change_1h > 0 %}text-success{% else %}text-muted{% endif %}">
                                {{ crypto.percent_change_1h }}
                            </td>
                            <td class="{% if crypto.percent_change_24h < 0 %}text-danger{% elif crypto.percent_change_24h > 0 %}text-success{% else %}text-muted{% endif %}">
                                {{ crypto.percent_change_24h }}
                            </td>
                            <td><i class="currency-icon"></i> {{ crypto.market_cap }}</td>
                            <td><i class="currency-icon"></i> {{ crypto.volume_24h }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div style="display: flex; width: 100%; height: 100%; align-items: center; flex-direction: column; text-align: center; line-height: 1.5;">
                    <h3 style="font-size: 40px; margin: 24px 0 0; font-weight: 600; line-height: 1.4;">
                        Your watchlist is empty.
                    </h3>
                    <p style="margin: 8px 0 40px; font-size: 16px; color: #58667e; align-items: center; ">Start
                        building
                        your watchlist by clicking the button below.</p>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addAssetModal"
                            id="addAssetButton">
                        Add Asset
                    </button>
                    <br>
                </div>
            {% endif %}
        {% endif %}
        <div class="modal fade" id="addAssetModal" tabindex="-1" aria-labelledby="addAssetModalLabel"
             aria-hidden="true" style="box-sizing: border-box; margin: 0; padding: 0">
            <div class="modal-dialog modal-lg" role="document"
                 style="display: flex; align-items: center; justify-content: center; height: 100%;  box-sizing: border-box; width: 100%">
                <div class="modal-content" style="width: 300px">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addAssetModalLabel">Select Cryptocurrencies</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                        <form method="POST" action="










                                {% if selected_watchlist.id %}{% url 'core:watchlist' watchlist_id=selected_watchlist.id %}{% else %}{% url 'core:watchlist' %}{% endif %}">
                            {% csrf_token %}
                            <div class="crypto-list">
                                {{ form.cryptocurrencies }}
                            </div>
                            <button type="submit" class="btn btn-primary" style="width: 100%">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="selectWatchlistModal" tabindex="-1" aria-labelledby="selectWatchlistModalLabel"
             aria-hidden="true" style="box-sizing: border-box; margin: 0; padding: 0">
            <div class="modal-dialog modal-lg" role="document"
                 style="display: flex; align-items: center; justify-content: center; height: 100%;  box-sizing: border-box; width: 100%">
                <div class="modal-content" style="width: 300px">
                    <div class="modal-header">
                        <h5 class="modal-title" id="selectWatchlistModalLabel">Select Watchlist</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                        <ul id="watchlistDropdown" class="list-group">
                            {% for watchlist in user_watchlists %}
                                <li class="list-group-item">
                                    <a href="{% url 'core:watchlist' watchlist_id=watchlist.id %}"
                                       class="watchlist-link"
                                       style="text-decoration: none; color: inherit"
                                       data-id="{{ watchlist.id }}">{{ watchlist.name }}</a>
                                </li>
                            {% endfor %}
                            <br>
                            <br>
                            <a href="{% url 'core:create_watchlist' %}" class="btn btn-primary">Create a New
                                Watchlist</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="editNameModal" tabindex="-1" aria-labelledby="editNameModalLabel"
             aria-hidden="true" style="box-sizing: border-box; margin: 0; padding: 0">
            <div class="modal-dialog modal-lg" role="document"
                 style="display: flex; align-items: center; justify-content: center; height: 100%;  box-sizing: border-box; width: 100%">
                <div class="modal-content" style="width: 300px">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editNameModalLabel">Edit Watchlist Name</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                        <form method="POST" action="











                                {% if selected_watchlist.id %}{% url 'core:edit_watchlist_name' watchlist_id=selected_watchlist.id %}{% endif %}">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">Name</span>
                                </div>
                                <input type="text" class="form-control" placeholder="Username"
                                       aria-label="Watchlist Name"
                                       aria-describedby="basic-addon1"
                                       name="name"
                                       value="{{ selected_watchlist.name }}"
                                >
                            </div>
                            <br>
                            <br>
                            <button type="submit" class="btn btn-primary" style="width: 100%">Save</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let listItems = document.querySelectorAll('.list-group-item');

            listItems.forEach(function (item) {
                item.addEventListener('mouseover', function () {
                    this.classList.add('active');
                });

                item.addEventListener('mouseout', function () {
                    this.classList.remove('active');
                });
            });

            let addAssetModal = new bootstrap.Modal(document.getElementById('addAssetModal'));
            let watchlistModal = new bootstrap.Modal(document.getElementById('selectWatchlistModal'));
            let editNameModal = new bootstrap.Modal(document.getElementById('editNameModal'));
            document.getElementById('addAssetButton').addEventListener('click', function () {
                addAssetModal.show();
                watchlistModal.hide();
                editNameModal.hide();
            });

            document.getElementById('toggleWatchlists').addEventListener('click', function () {
                addAssetModal.hide();
                watchlistModal.show();
                editNameModal.hide();
            });

            document.getElementById('editNameBtn').addEventListener('click', function () {
                addAssetModal.hide();
                watchlistModal.hide();
                editNameModal.show();
            })
        });

        const currencyIcons = {
            'USD': 'fas fa-dollar-sign',
            'AUD': 'fas fa-dollar-sign',
            'CAD': 'fas fa-dollar-sign',
            'CNY': 'fas fa-yen-sign',
            'EUR': 'fas fa-euro-sign',
            'INR': 'fas fa-rupee-sign',
            'JPY': 'fas fa-yen-sign',
            'KWD': 'fas fa-money-bill-wave',
            'NZD': 'fas fa-dollar-sign',
            'PKR': 'fas fa-rupee-sign',
            'RUB': 'fas fa-ruble-sign',
            'AED': 'fas fa-money-bill-wave'
        };

        function updateCurrencyIcon(currencyCode) {
            const iconClass = currencyIcons[currencyCode];
            if (iconClass) {
                const currencyElements = document.querySelectorAll('.currency-icon');
                currencyElements.forEach(element => {
                    element.className = `currency-icon ${iconClass}`;
                });
            }
        }

        updateCurrencyIcon('{{ session_cur }}');

    </script>
{% endblock %}