CryptoNexa-dev/CryptoNexa/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from CryptoNexa import views, settings

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', views.index, name='index'),
  path('', include('core.urls')),
  path('', include('Newsletter.urls')),
  path('', include('ContactUS.urls')),
  path('currencyExchange/', include('currencyExchange.urls')),
  path('', include('payments.urls')),
  path('', include('BuySell.urls')),
  path('', include('portfolio.urls')),
  path('', include('support.urls')),
  path('filter_crypto_data', views.filter_crypto_data, name='filter_crypto_data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CryptoNexa-dev/core/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'core'

urlpatterns = [
    path('register/', csrf_exempt(views.register), name='register'),
    path('login/', csrf_exempt(views.user_login), name='login'),
    path('logout/', csrf_exempt(views.user_logout), name='logout'),
    path('profile/<int:id>', csrf_exempt(views.user_profile), name='profile'),
    path('edit_profile/<int:id>', csrf_exempt(views.user_edit_profile), name='edit_profile'),
    path('crypto/<slug:slug>/', views.crypto_detail, name='crypto_detail'),
    path('get_updated_crypto_data/<int:fetch_live_data>', views.get_updated_crypto_data,
         name='get_updated_crypto_data'),
    path('watchlist/', csrf_exempt(views.watchlist), name='watchlist'),
    path('watchlist/<int:watchlist_id>/', views.watchlist, name='watchlist'),
    path('create_watchlist/', csrf_exempt(views.create_watchlist), name='create_watchlist'),
    path('edit_watchlist_name/<int:watchlist_id>/', csrf_exempt(views.edit_watchlist_name), name='edit_watchlist_name'),
    path('payment_history/', csrf_exempt(views.payment_history), name='payment_history'),
    path('payment_history/',csrf_exempt(views.payment_history),name='payment_history'),
    path('currency_converter/',csrf_exempt(views.currency_converter), name='currency_converter')

    # Add other URL patterns as needed for your application
]

CryptoNexa-dev/templates/crypto/crypto_detail.html
{% extends 'CryptoNexa/base.html' %}
{% load static %}

{% block content %}
    <link href="{% static 'css/crypto_detail.css' %}" rel="stylesheet">
    <div class="container mt-5">

        {% if cryptocurrency %}
            <div class="row mt-4">

                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body" style="display: flex; flex-direction: column;">
                            <div style="display: flex; align-items: center;">
                                <img src="{{ cryptocurrency.logo }}" alt="{{ cryptocurrency.name }} Logo"
                                     style="width: 50px; height: 50px; margin-right: 10px;"/>
                                <h2>{{ cryptocurrency.name }}</h2>
                            </div>
                            <br />
                            <p>{{ cryptocurrency.description }}</p>
                            <a href="{{ cryptocurrency.website }}" target="_blank">Visit Website</a>
                        </div>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'buysell' slug=cryptocurrency.slug name=cryptocurrency.name price=cryptocurrency.price %}"
                           class="btn btn-add-transaction">Add Transaction</a>
                    </div>
                </div>

                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h4 class="text-center">Quote Information</h4>
                                    <br />
                                    <br />
                                    <table class="table table-striped">
                                        <tbody>
                                        <tr>
                                            <td><strong>Price {{ session_cur }}:</strong></td>
                                            <td><i class="currency-icon"></i><span class="price-class"> {{ cryptocurrency.price }}</span></td>
                                        </tr>
                                        <tr>
                                            <td><strong>24h Volume:</strong></td>
                                            <td><i class="currency-icon"></i><span class="price-class"> {{ cryptocurrency.volume_24h }}</span></td>
                                        </tr>
                                        <tr>
                                            <td><strong>24h Volume Change:</strong></td>
                                            <td>{{ cryptocurrency.volume_change_24h }}%</td>
                                        </tr>
                                        <tr>
                                            <td><strong>1h Change:</strong></td>
                                            <td>{{ cryptocurrency.percent_change_1h }}%</td>
                                        </tr>
                                        <tr>
                                            <td><strong>24h Change:</strong></td>
                                            <td>{{ cryptocurrency.percent_change_24h }}%</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="text-center">Details</h4>
                                    <br />
                                    <br />
                                    <table class="table table-striped">
                                        <tbody>
                                        <tr>
                                            <td><strong>Number of Market Pairs:</strong></td>
                                            <td>{{ cryptocurrency.num_market_pairs }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Circulating Supply:</strong></td>
                                            <td>{{ cryptocurrency.circulating_supply }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Total Supply:</strong></td>
                                            <td>{{ cryptocurrency.total_supply }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Max Supply:</strong></td>
                                            <td>{{ cryptocurrency.max_supply }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Infinite Supply:</strong></td>
                                            <td>{{ cryptocurrency.infinite_supply }}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        {% else %}
            <div class="alert alert-danger mt-3">
                Cryptocurrency not found
            </div>
        {% endif %}
    </div>

    <script>
        // Your existing JavaScript for updating currency icons can remain unchanged
        const currencyIcons = {
            'USD': 'fas fa-dollar-sign',
            'AUD': 'fas fa-dollar-sign',
            'CAD': 'fas fa-dollar-sign',
            'CNY': 'fas fa-yen-sign',
            'EUR': 'fas fa-euro-sign',
            'INR': 'fas fa-rupee-sign',
            'JPY': 'fas fa-yen-sign',
            'KWD': 'fas fa-money-bill-wave',
            'NZD': 'fas fa-dollar-sign',
            'PKR': 'fas fa-rupee-sign',
            'RUB': 'fas fa-ruble-sign',
            'AED': 'fas fa-money-bill-wave'
        };

        function updateCurrencyIcon(currencyCode) {
            const iconClass = currencyIcons[currencyCode];
            if (iconClass) {
                const currencyElements = document.querySelectorAll('.currency-icon');
                currencyElements.forEach(element => {
                    element.className = `currency-icon ${iconClass}`;
                });
            }
        }

        updateCurrencyIcon('{{ session_cur }}');
    </script>
{% endblock %}

CryptoNexa-dev/templates/crypto/crypto_list_filter_modal.html
{% extends 'CryptoNexa/index.html' %}
{% load static %}

{% block crypto_filter %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const myModal = new bootstrap.Modal(document.getElementById("crypto-filter-modal"), {
            backdrop: 'static',
            keyboard: false
        });
        myModal.show();

        const modalBackdrop = document.querySelector('.modal-backdrop');
        modalBackdrop.addEventListener('click', function(event) {
            event.stopPropagation();
        });
    });
</script>

<div class="modal fade" id="crypto-filter-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLabel">Choose your filters</h5>
            </div>
            <div class="modal-body">

                <form method="POST" action="{% url 'filter_crypto_data' %}">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>Error!</strong> Please correct the following errors:
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CryptoNexa-dev/templates/crypto/crypto_list_view.html
{% block cryptoListView %}
    {% load static %}

    <link href="{% static 'css/crypto_table.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <div class="container">
        <br/>
        <a href="{% url 'filter_crypto_data' %}" id="openModal" class="button-link">
            <button style="float: right; width: 7%; height: 25%;" type="button" id="filter-button"
                    class="btn btn-outline-primary">Filter
            </button>
        </a>
        {% if error_message %}
            <h1>{{ error_message }}</h1>
        {% else %}
            <table class="table table-striped fixed-table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th><i class="currency-icon"></i> Price {{ session_cur }}</th>
                    <th>1h%</th>
                    <th>24h%</th>
                    <th><i class="currency-icon"></i> MarketCap</th>
                    <th><i class="currency-icon"></i> Volume (24h)</th>
                </tr>
                </thead>
                <tbody id="crypto-table-body">
                {% for crypto in cryptos %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'core:crypto_detail' crypto.slug %}">{{ crypto.name }}</a></td>
                        <td>
                            <div id="price-{{ crypto.id }}"><i class="currency-icon"></i><span class="price-class"> {{ crypto.price }}</span></div>
                        </td>
                        <td id="change-1h-{{ crypto.id }}"
                            class="{% if crypto.percent_change_1h < 0 %}text-danger{% elif crypto.percent_change_1h > 0 %}text-success{% else %}text-muted{% endif %}">
                            {{ crypto.percent_change_1h }}
                        </td>
                        <td id="change-24h-{{ crypto.id }}"
                            class="{% if crypto.percent_change_24h < 0 %}text-danger{% elif crypto.percent_change_24h > 0 %}text-success{% else %}text-muted{% endif %}">
                            {{ crypto.percent_change_24h }}
                        </td>
                        <td id="market-cap-{{ crypto.id }}"><i class="currency-icon"></i><span class="price-class"> {{ crypto.market_cap }}</span></td>
                        <td id="volume-24h-{{ crypto.id }}"><i class="currency-icon"></i><span class="price-class"> {{ crypto.volume_24h }}</span></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    {% if not error_message and update_values %}
        <script>
            const currencyIcons = {
                'USD': 'fas fa-dollar-sign',
                'AUD': 'fas fa-dollar-sign',
                'CAD': 'fas fa-dollar-sign',
                'CNY': 'fas fa-yen-sign',
                'EUR': 'fas fa-euro-sign',
                'INR': 'fas fa-rupee-sign',
                'JPY': 'fas fa-yen-sign',
                'KWD': 'fas fa-money-bill-wave',
                'NZD': 'fas fa-dollar-sign',
                'PKR': 'fas fa-rupee-sign',
                'RUB': 'fas fa-ruble-sign',
                'AED': 'fas fa-money-bill-wave'
            };

            function updateCurrencyIcon(currencyCode) {
                const iconClass = currencyIcons[currencyCode];
                if (iconClass) {
                    const currencyElements = document.querySelectorAll('.currency-icon');
                    currencyElements.forEach(element => {
                        element.className = `currency-icon ${iconClass}`;
                    });
                }
            }

            updateCurrencyIcon('{{ session_cur }}');

            function updateCryptoData() {
                fetch('{% url 'core:get_updated_crypto_data' fetch_live_data=0 %}')
                    .then(response => response.json())
                    .then(data => {
                        data.forEach(crypto => {
                            const cryptoId = crypto.id;
                            document.getElementById(`price-${cryptoId}`).querySelector('.price-class').innerText = ` ${crypto.price}`;
                            document.getElementById(`change-1h-${cryptoId}`).innerText = crypto.percent_change_1h;
                            document.getElementById(`change-24h-${cryptoId}`).innerText = crypto.percent_change_24h;
                            document.getElementById(`market-cap-${cryptoId}`).querySelector('.price-class').innerText = ` ${crypto.market_cap}`;
                            document.getElementById(`volume-24h-${cryptoId}`).querySelector('.price-class').innerText = ` ${crypto.volume_24h}`;
                            document.getElementById(`change-1h-${cryptoId}`).classList = calculateChangeClass(crypto.percent_change_1h);
                            document.getElementById(`change-24h-${cryptoId}`).classList = calculateChangeClass(crypto.percent_change_24h);
                        });
                    })
                    .catch(error => {
                        console.error('Error fetching crypto data:', error);
                    });
            }

            function calculateChangeClass(change) {
                if (change < 0) {
                    return 'text-danger';
                } else if (change > 0) {
                    return 'text-success';
                } else {
                    return 'text-muted';
                }
            }

            setInterval(updateCryptoData, 2000);
            updateCryptoData();

        </script>
    {% endif %}
{% endblock %}

CryptoNexa-dev/templates/crypto/filtered_crypto_data.html
{% block filtered_crypto_block %}
    {% load static %}
    <link href="{% static 'css/crypto_table.css' %}" rel="stylesheet">
    <div class="container">
        <br/>
        <a href="{% url 'filter_crypto_data' %}" id="openModal" class="button-link">
            <button style="float: right; width: 7%; height: 25%;" type="button" id="filter-button"
                    class="btn btn-outline-primary">Filter
            </button>
        </a>
        {% if error_message %}
            <h1>{{ error_message }}</h1>
        {% else %}
            <table class="table fixed-table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th><i class="currency-icon"></i> Price {{ session_cur }}</th>
                    <th>1h%</th>
                    <th>24h%</th>
                    <th><i class="currency-icon"></i> MarketCap</th>
                    <th><i class="currency-icon"></i> Volume (24h)</th>
                </tr>
                </thead>
                <tbody id="crypto-table-body">
                {% for crypto in cryptos %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'core:crypto_detail' crypto.slug %}">{{ crypto.name }}</a></td>
                        <td id="price-{{ crypto.id }}"><i class="currency-icon"></i> {{ crypto.price }}</td>
                        <td id="change-1h-{{ crypto.id }}"
                            class="{% if crypto.percent_change_1h < 0 %}text-danger{% elif crypto.percent_change_1h > 0 %}text-success{% else %}text-muted{% endif %}">
                            {{ crypto.percent_change_1h }}
                        </td>
                        <td id="change-24h-{{ crypto.id }}"
                            class="{% if crypto.percent_change_24h < 0 %}text-danger{% elif crypto.percent_change_24h > 0 %}text-success{% else %}text-muted{% endif %}">
                            {{ crypto.percent_change_24h }}
                        </td>
                        <td id="market-cap-{{ crypto.id }}"><i class="currency-icon"></i> {{ crypto.market_cap }}</td>
                        <td id="volume-24h-{{ crypto.id }}"><i class="currency-icon"></i> {{ crypto.volume_24h }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

    </div>

    <script>
        const currencyIcons = {
            'USD': 'fas fa-dollar-sign',
            'AUD': 'fas fa-dollar-sign',
            'CAD': 'fas fa-dollar-sign',
            'CNY': 'fas fa-yen-sign',
            'EUR': 'fas fa-euro-sign',
            'INR': 'fas fa-rupee-sign',
            'JPY': 'fas fa-yen-sign',
            'KWD': 'fas fa-money-bill-wave',
            'NZD': 'fas fa-dollar-sign',
            'PKR': 'fas fa-rupee-sign',
            'RUB': 'fas fa-ruble-sign',
            'AED': 'fas fa-money-bill-wave'
        };

        function updateCurrencyIcon(currencyCode) {
            const iconClass = currencyIcons[currencyCode];
            if (iconClass) {
                const currencyElements = document.querySelectorAll('.currency-icon');
                currencyElements.forEach(element => {
                    element.className = `currency-icon ${iconClass}`;
                });
            }
        }

        updateCurrencyIcon('{{ session_cur }}');
    </script>


{% endblock %}

CryptoNexa-dev/templates/crypto/highlights.html
<head>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const switchElement = document.getElementById('highlightSwitch');
            const highlightsDiv = document.getElementById('highlightsDiv');
            switchElement.addEventListener('change', function () {
                highlightsDiv.style.display = switchElement.checked ? 'block' : 'none';
            });
        });
    </script>
</head>
<div style="display: flex; margin-left: 100px; margin-right: 100px;">
    <div style="display: flex; flex-direction: column; padding: 24px 0px; width: 80%;">
        <h1 style="font-size: 24px; font-weight: 700">Today's Cryptocurrency Prices by Market Cap</h1>
        <p style="font-size: 14px">The global crypto market cap is $1.44T, a <span
                style="color: #16c784">0.57% </span>increase over the last day.</p>
    </div>
    <div style="display: flex; align-items: center; padding: 24px 0px; width: 20%;">
        <div class="form-check form-switch" style="width: 100%; position: relative; align-items: center">
            <label class="form-check-label" for="highlightSwitch"
                   style="font-size: 18px; color: #58667e; position: absolute; margin-right: 68px; right: 0">Highlights </label>
            <input class="form-check-input" type="checkbox" role="switch" id="highlightSwitch"
                   style="position:absolute; right: 0; width: 48px; height: 24px;" unchecked>
        </div>
    </div>
</div>
<div id="highlightsDiv"
     style="display: none; margin-top: 10px; height: 200px;  padding: 10px; box-sizing: border-box; margin-left: 100px; margin-right: 100px;">

    <!-- Sub divs within the highlights div -->
    <div style="height: 100%; width: calc(33.33% - 10px); background-color: white; float: left; margin-right: 10px; padding: 16px; box-shadow: rgba(88, 102, 126, 0.08) 0px 4px 24px, rgba(88, 102, 126, 0.12) 0px 1px 2px; border-radius: 8px; overflow: hidden;">
        <div style="display: flex; align-items: center; height: 26px; margin-bottom: 6px; white-space: nowrap; overflow: hidden;}">
            <img src="/static/images/TrendingIcon.png" style="width: 20px; height: 20px"/>
            <h3 style="margin-left:10px; font-weight: bold; font-size: 16px; overflow: hidden; text-overflow: ellipsis; }">
                Trending</h3>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">1</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/creditcoin.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">CreditCoin</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">CTC</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #16c784">5.81%</span>
            </div>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">2</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/selo.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">SELO+</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">SELO</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #16c784">18.90%</span>
            </div>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">3</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/alphadex.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">AlphaDEX</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">ROAR</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #ea3943">23.91%</span>
            </div>
        </div>

    </div>
    <div style="height: 100%; width: calc(33.33% - 10px); background-color: white; float: left; margin-right: 10px; padding: 16px; box-shadow: rgba(88, 102, 126, 0.08) 0px 4px 24px, rgba(88, 102, 126, 0.12) 0px 1px 2px; border-radius: 8px; overflow: hidden;">
        <div style="display: flex; align-items: center; height: 26px; margin-bottom: 6px; white-space: nowrap; overflow: hidden;}">
            <img src="/static/images/RecentlyAddedIcon.png" style="width: 20px; height: 20px"/>
            <h3 style="margin-left:10px; font-weight: bold; font-size: 16px; overflow: hidden; text-overflow: ellipsis; }">
                Recently Added</h3>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">1</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/jeff.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">Jeff World</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">JEFF</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #000">$0.07398</span>
            </div>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">2</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/javelin.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">Javelin</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">JVL</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #000">$0.0006033</span>
            </div>
        </div>
        <div style="display: flex; -webkit-box-pack: justify; justify-content: space-between; -webkit-box-align: center; align-items: center; height: 40px; cursor: pointer; white-space: nowrap; padding-left: 9px; gap: 10px;}">
            <div style="display: flex; align-items: center;">
                <span style="font-size: 12px; line-height: 18px; color: #808a9d; font-family: sans-serif; }">3</span>
                <div style="margin-left:16px; ">
                    <img src="/static/images/mmx.png" style="height: 24px; width: 24px">
                    <span style="margin-left: 8px; font-size: 12px; font-weight: 600;">MMX</span>
                </div>
                <span style="margin-left: 8px; color: #808a9d; font-size: 12px">MMX</span>
            </div>
            <div>
                <span style="font-size: 12px; font-weight: 500; color: #000">$3.2692</span>
            </div>
        </div>

    </div>
    <div style="height: 100%; width: calc(33.33% - 10px); background-color: white; float: left; padding: 16px; box-shadow: rgba(88, 102, 126, 0.08) 0px 4px 24px, rgba(88, 102, 126, 0.12) 0px 1px 2px; border-radius: 8px; overflow: hidden;">
        <div style="display: flex; align-items: center; height: 26px; margin-bottom: 6px; white-space: nowrap; overflow: hidden;}">
            <h3 style="margin-left:10px; font-weight: bold; font-size: 16px; overflow: hidden; text-overflow: ellipsis; }">
                Fear & Greed Index </h3>
        </div>
        <div style="display: flex; align-items: center; justify-content: center; position: relative">
            <img src="/static/images/fearGreed.jpg" style="width: 200px; height: 170px"/>
        </div>
    </div>

    <div style="clear: both;"></div> <!-- Clear the float -->

</div>